parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: terraformRootFolderPath
  displayName: 'Terraform root folder path'
  type: string
  default: '.terraform'

- name: terraformEnvironmentFolderPaths
  displayName: 'List of Terraform environment folder paths'
  type: object
  default: []

- name: terraformArtifactName
  displayName: 'Terraform artifact name'
  type: string
  default: 'terraform'

- name: buildConfiguration
  displayName: 'Build configuration'
  type: string
  default: 'Release'

- name: preBuildSteps
  displayName: 'Steps to run before build'
  type: stepList
  default: []

- name: enableSonarCloud
  displayName: 'Enable SonarCloud'
  type: boolean
  default: true

- name: sonarCloudOrganizationName
  displayName: 'Organization name for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectKey
  displayName: 'Project key for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectName
  displayName: 'Project name for SonarCloud'
  type: string
  default: ''

- name: dotNetSDKVersions
  displayName: '.NET Core SDK versions'
  type: object
  default: []

- name: codeCoverageSettingsFullPath
  displayName: 'The path of the code coverage settings file'
  type: string
  default: '.runsettings'

- name: restoreOnlyFromNuGetFeed
  displayName: 'Restore only from NuGet feed'
  type: boolean
  default: true

- name: nugetConfigPath
  displayName: 'NuGet configuration path'
  type: string
  default: ''

- name: internalFeed
  displayName: 'Internal feed'
  type: string
  default: ''

- name: enableDotNetFormat
  displayName: 'Verify that all code is correctly formatted'
  type: boolean
  default: true

- name: enableNuGetValidationOutdatedPackages
  displayName: 'Enable NuGet validation of outdated packages'
  type: boolean
  default: true

- name: mutationTestingLevel
  displayName: 'Mutation testing level'
  type: string
  default: 'Complete'

- name: mutationTestingProjects
  displayName: 'List of projects for mutation testing using Stryker'
  type: object
  default: []

- name: enableReSharperInspectCode
  displayName: 'Enable ReSharper inspect code'
  type: boolean
  default: true

- name: checkWarnings
  displayName: 'Check warnings'
  type: boolean
  default: true

- name: checkCoverage
  displayName: 'Check code coverage'
  type: boolean
  default: true

- name: includeSonarcloudBuildBreaker
  displayName: 'Does Sonarcloud build breaker turn on?'
  type: boolean
  default: true

- name: checkMutationTesting
  displayName: 'Check mutation testing'
  type: boolean
  default: true

- name: projectArtifactName
  displayName: 'Project artifact name'
  type: string
  default: 'project'

- name: migrationArtifactName
  displayName: 'Migrations artifact name'
  type: string
  default: 'migrations'

- name: migrationProjectPath
  displayName: 'Migrations project path'
  type: string
  default: 'database/src/Database'

- name: migrationDbContexts
  displayName: 'Migrations database contexts'
  type: object
  default: []

stages:
- stage: Build
  displayName: 'Build'

  jobs:
  - template: '../Terraform/CI.yml'
    parameters:
      rootFolderPath: ${{ parameters.terraformRootFolderPath }}
      environmentFolderPaths: ${{ parameters.terraformEnvironmentFolderPaths }}
      artifactName: ${{ parameters.terraformArtifactName }}

  - job: Build
    displayName: 'Build'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: Terraform
    condition: eq(dependencies.Terraform.result, 'Succeeded')
    steps:
    - template: 'build.yml'
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        preBuildSteps: ${{ parameters.preBuildSteps }}
        enableSonarCloud: ${{ parameters.enableSonarCloud }}
        sonarCloudOrganizationName: ${{ parameters.sonarCloudOrganizationName }}
        sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
        sonarCloudProjectName: ${{ parameters.sonarCloudProjectName }}
        dotNetSDKVersions: ${{ parameters.dotNetSDKVersions }}
        codeCoverageSettingsFullPath: ${{ parameters.codeCoverageSettingsFullPath }}
        restoreOnlyFromNuGetFeed: ${{ parameters.restoreOnlyFromNuGetFeed }}
        nugetConfigPath: ${{ parameters.nugetConfigPath }}
        internalFeed: ${{ parameters.internalFeed }}
        enableDotNetFormat: ${{ parameters.enableDotNetFormat }}
        enableNuGetValidationOutdatedPackages: ${{ parameters.enableNuGetValidationOutdatedPackages }}
        mutationTestingLevel: ${{ parameters.mutationTestingLevel }}
        mutationTestingProjects: ${{ parameters.mutationTestingProjects }}
        enableReSharperInspectCode: ${{ parameters.enableReSharperInspectCode }}
        checkWarnings: ${{ parameters.checkWarnings }}
        checkCoverage: ${{ parameters.checkCoverage }}
        includeSonarcloudBuildBreaker: ${{ parameters.includeSonarcloudBuildBreaker }}
        checkMutationTesting: ${{ parameters.checkMutationTesting }}

  - job: Publish
    displayName: 'Publish'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: Build
    condition: eq(dependencies.Build.result, 'Succeeded')
    steps:
    - template: 'publish.yml'
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        projectArtifactName: ${{ parameters.projectArtifactName }}

  - job: Migrations
    displayName: 'Migrations'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: Publish
    condition: eq(dependencies.Publish.result, 'Succeeded')
    steps:
    - template: 'migrations.yml'
      parameters:
        migrationArtifactName: ${{ parameters.migrationArtifactName }}
        migrationProjectPath: ${{ parameters.migrationProjectPath }}
        migrationDbContexts: ${{ parameters.migrationDbContexts }}
