parameters:
- name: rootFolderPath
  displayName: 'Terraform root folder path'
  type: string
  default: '.terraform'

- name: environmentFolderPaths
  displayName: 'List of Terraform environment folder paths'
  type: object
  default: []

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  condition: |
    and
    (
      succeeded(),
      ${{ gt(length(parameters.environmentFolderPaths), 0) }}
    )
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: 'Terraform recursive format check /${{ parameters.rootFolderPath }}'
  condition: |
    and
    (
      succeeded(),
      ${{ gt(length(parameters.environmentFolderPaths), 0) }}
    )
  inputs:
    command: 'fmt'
    workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.rootFolderPath }}'
    commandOptions: '-recursive -check'

- ${{ each environmentFolderPath in parameters.environmentFolderPaths }}:
  - task: TerraformCLI@0
    displayName: 'Terraform init for path /${{ parameters.rootFolderPath }}/${{ environmentFolderPath }}'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.rootFolderPath }}/${{ environmentFolderPath }}'
      commandOptions: '-backend=false'

  - task: TerraformCLI@0
    displayName: 'Terraform validate for path /${{ parameters.rootFolderPath }}/${{ environmentFolderPath }}'
    inputs:
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.rootFolderPath }}/${{ environmentFolderPath }}'
