parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: rootFolderPath
  displayName: 'Terraform root folder path'
  type: string
  default: '.terraform'

- name: environmentFolderPaths
  displayName: 'List of Terraform environment folder paths'
  type: object
  default: []

- name: artifactName
  displayName: 'Terraform artifact name'
  type: string
  default: 'terraform'

jobs:
- job: Terraform
  displayName: 'Terraform'
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: 'publish.yml'
    parameters:
      rootFolderPath: ${{ parameters.rootFolderPath }}
      environmentFolderPaths: ${{ parameters.environmentFolderPaths }}
      artifactName: ${{ parameters.artifactName }}

  - template: 'build.yml'
    parameters:
      rootFolderPath: ${{ parameters.rootFolderPath }}
      environmentFolderPaths: ${{ parameters.environmentFolderPaths }}
