parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: environmentName
  displayName: 'Environment name'
  type: string
  default: ''

- name: variableGroups
  displayName: 'Variable group list'
  type: object
  default: []

- name: ciPipelineResourceName
  displayName: 'CI pipeline resource name'
  type: string
  default: 'ci'

- name: artifactName
  displayName: 'Terraform artifact name'
  type: string
  default: 'terraform'

- name: workingDirectoryPath
  displayName: 'Path to Terraform folder'
  type: string
  default: ''

- name: azureServiceConnectionName
  displayName: 'Backend Azure Service Connection'
  type: string
  default: ''

- name: azureResourceGroupName
  displayName: 'Azure Resource Group Name'
  type: string
  default: ''

- name: azureResourceGroupLocation
  displayName: 'Azure Resource Group Location'
  type: string
  default: 'westeurope'

- name: azureStorageAccountName
  displayName: 'Azure Storage Account Name'
  type: string
  default: ''

- name: azureStorageContainerName
  displayName: 'Azure Storage Container Name'
  type: string
  default: ''

- name: enableSqlFirewallRuleForBuildAgentIPAddress
  displayName: 'Creates (then removes) SQL firewall rule for Build Agent IP address'
  type: boolean
  default: false

- name: sqlServerResourceGroupName
  type: string
  default: ''

- name: sqlServerName
  type: string
  default: ''

- name: planCommandVariables
  displayName: 'Plan command variables'
  type: string
  default: ''

- name: notifyUsers
  displayName: 'Notify users'
  type: string
  default: '[$(System.TeamProject)]\Build Administrators'

- name: enableOutputVariables
  displayName: 'Enable output variables'
  type: boolean
  default: false

jobs:
- deployment: TerraformPlan
  displayName: 'Terraform plan'
  pool:
    vmImage: ${{ parameters.vmImage }}
  environment: ${{ parameters.environmentName }}
  variables:
  - ${{ each variableGroup in parameters.variableGroups }}:
    - group: ${{ variableGroup }}
  - name: artifactWorkingDirectory
    value: '$(Pipeline.Workspace)/${{ parameters.ciPipelineResourceName }}/${{ parameters.artifactName }}/${{ parameters.workingDirectoryPath }}'
  - name: azureStorageContainerName
    value: ${{ coalesce(parameters.azureStorageContainerName, lower(parameters.environmentName)) }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ${{ parameters.ciPipelineResourceName }}
          displayName: 'Download artifact ''${{ parameters.artifactName }}'''
          artifact: ${{ parameters.artifactName }}

        - task: TerraformInstaller@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformCLI@0
          displayName: 'Terraform init'
          inputs:
            command: 'init'
            workingDirectory: '$(artifactWorkingDirectory)'
            backendType: 'azurerm'
            backendServiceArm: '${{ parameters.azureServiceConnectionName }}'
            ensureBackend: false
            backendAzureRmResourceGroupName: '${{ parameters.azureResourceGroupName }}'
            backendAzureRmResourceGroupLocation: '${{ parameters.azureResourceGroupLocation }}'
            backendAzureRmStorageAccountName: '${{ parameters.azureStorageAccountName }}'
            backendAzureRmContainerName: '$(azureStorageContainerName)'
            commandOptions: '-input=false'

        - ${{ if eq(parameters.enableSqlFirewallRuleForBuildAgentIPAddress, true) }}:
          - template: '../AzureDevOps/create-sql-server-firewall-rule-for-build-agent-ip-address.yml'
            parameters:
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              resourceGroupName: ${{ parameters.sqlServerResourceGroupName }}
              sqlServerName: ${{ parameters.sqlServerName }}

        - task: TerraformCLI@0
          displayName: 'Terraform plan'
          inputs:
            command: 'plan'
            workingDirectory: '$(artifactWorkingDirectory)'
            environmentServiceName: '${{ parameters.azureServiceConnectionName }}'
            publishPlanResults: '${{ parameters.environmentName }}'
            commandOptions: '-out=$(artifactWorkingDirectory)/${{ parameters.environmentName }}.tfplan -input=false -detailed-exitcode ${{ parameters.planCommandVariables }}'

        - ${{ if eq(parameters.enableSqlFirewallRuleForBuildAgentIPAddress, true) }}:
          - template: '../Azure/SqlServer/delete-firewall-rule.yml'
            parameters:
              condition: 'always()'
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              resourceGroupName: ${{ parameters.sqlServerResourceGroupName }}
              sqlServerName: ${{ parameters.sqlServerName }}

        - task: TerraformCLI@0
          displayName: 'Terraform show'
          condition: |
            and
            (
              succeeded(),
              eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true')
            )
          inputs:
            command: 'show'
            workingDirectory: '$(artifactWorkingDirectory)'
            inputTargetPlanOrStateFilePath: '$(artifactWorkingDirectory)/${{ parameters.environmentName }}.tfplan'

        - bash: |
            echo "##vso[task.setvariable variable=HAS_CHANGES;isoutput=true;isreadonly=true;]$TERRAFORM_PLAN_HAS_CHANGES"
            echo "##vso[task.setvariable variable=HAS_DESTROY_CHANGES;isoutput=true;isreadonly=true;]$TERRAFORM_PLAN_HAS_DESTROY_CHANGES"
          displayName: 'Set Terraform plan output variables'
          condition: |
            and
            (
              succeeded(),
              eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true')
            )
          name: tfplanOutput

- job: TerraformValidate
  displayName: 'Terraform validate'
  pool: server
  timeoutInMinutes: 7200 # job times out in 5 days
  dependsOn: TerraformPlan
  condition: |
    and
    (
      succeeded(),
      eq(dependencies.TerraformPlan.outputs['TerraformPlan.tfplanOutput.HAS_DESTROY_CHANGES'], 'true')
    )
  steps:
  - task: ManualValidation@0
    displayName: 'Manual validation'
    timeoutInMinutes: 4320 # task times out in 3 days
    inputs:
      notifyUsers: '${{ parameters.notifyUsers }}'
      instructions: 'Terraform plan has DESTROY changes, please review ''${{ parameters.environmentName }}'''

- deployment: TerraformApply
  displayName: 'Terraform apply'
  pool:
    vmImage: ${{ parameters.vmImage }}
  environment: ${{ parameters.environmentName }}
  dependsOn: TerraformValidate
  condition: |
    and
    (
      not(failed()),
      or
      (
        eq(dependencies.TerraformPlan.outputs['TerraformPlan.tfplanOutput.HAS_CHANGES'], 'true'),
        eq(${{ parameters.enableOutputVariables }}, true)
      ),
      in(dependencies.TerraformValidate.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    )
  variables:
  - ${{ each variableGroup in parameters.variableGroups }}:
    - group: ${{ variableGroup }}
  - name: artifactWorkingDirectory
    value: '$(Pipeline.Workspace)/${{ parameters.ciPipelineResourceName }}/${{ parameters.artifactName }}/${{ parameters.workingDirectoryPath }}'
  - name: azureStorageContainerName
    value: ${{ coalesce(parameters.azureStorageContainerName, lower(parameters.environmentName)) }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ${{ parameters.ciPipelineResourceName }}
          displayName: 'Download artifact ''${{ parameters.artifactName }}'''
          artifact: ${{ parameters.artifactName }}

        - task: TerraformInstaller@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformCLI@0
          displayName: 'Terraform init'
          inputs:
            command: 'init'
            workingDirectory: '$(artifactWorkingDirectory)'
            backendType: 'azurerm'
            backendServiceArm: '${{ parameters.azureServiceConnectionName }}'
            ensureBackend: false
            backendAzureRmResourceGroupName: '${{ parameters.azureResourceGroupName }}'
            backendAzureRmResourceGroupLocation: '${{ parameters.azureResourceGroupLocation }}'
            backendAzureRmStorageAccountName: '${{ parameters.azureStorageAccountName }}'
            backendAzureRmContainerName: '$(azureStorageContainerName)'
            commandOptions: '-input=false'

        - ${{ if eq(parameters.enableSqlFirewallRuleForBuildAgentIPAddress, true) }}:
          - template: '../AzureDevOps/create-sql-server-firewall-rule-for-build-agent-ip-address.yml'
            parameters:
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              resourceGroupName: ${{ parameters.sqlServerResourceGroupName }}
              sqlServerName: ${{ parameters.sqlServerName }}

        - task: TerraformCLI@0
          displayName: 'Terraform apply'
          inputs:
            command: 'apply'
            workingDirectory: '$(artifactWorkingDirectory)'
            environmentServiceName: '${{ parameters.azureServiceConnectionName }}'
            commandOptions: '-input=false -auto-approve ${{ parameters.planCommandVariables }}'

        - ${{ if eq(parameters.enableSqlFirewallRuleForBuildAgentIPAddress, true) }}:
          - template: '../Azure/SqlServer/delete-firewall-rule.yml'
            parameters:
              condition: 'always()'
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              resourceGroupName: ${{ parameters.sqlServerResourceGroupName }}
              sqlServerName: ${{ parameters.sqlServerName }}

        - task: TerraformCLI@0
          name: TerraformOutput
          displayName: 'Terraform output variables'
          condition: |
            and
            (
              succeeded(),
              eq(${{ parameters.enableOutputVariables }}, true)
            )
          inputs:
            command: 'output'
            workingDirectory: '$(artifactWorkingDirectory)'
