parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: terraformRootFolderPath
  displayName: 'Terraform root folder path'
  type: string
  default: '.terraform'

- name: terraformEnvironmentFolderPaths
  displayName: 'List of Terraform environment folder paths'
  type: object
  default: []

jobs:
- job: Terraform
  displayName: 'Terraform'
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: 'build.yml'
    parameters:
      rootFolderPath: ${{ parameters.terraformRootFolderPath }}
      environmentFolderPaths: ${{ parameters.terraformEnvironmentFolderPaths }}
