parameters:
- name: vmImage
  type: string
  default: 'ubuntu-latest'
- name: stageName
  type: string
  default: 'N/A'
- name: environment
  type: string
  default: 'N/A'
- name: dependsOn
  type: string
  default: 'N/A'
- name: appName
  type: string
  default: 'N/A'
- name: azureSubscription
  type: string
  default: 'N/A'
- name: resourceGroupName
  type: string
  default: 'N/A'

stages:
- stage: ${{ parameters.stageName }}
  displayName: '${{ parameters.stageName }} stage'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: 'Replace values in appsettings.json'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              appName: ${{ parameters.appName }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              appSettings: |
                [
                  {
                    "name": "TestVariable",
                    "value": "test upated",
                    "slotSetting": false
                  },
                  {
                    "name": "ApiSecurityConfig__Audience",
                    "value": "news Updated",
                    "slotSetting": false
                  }
                ]

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy in App Services'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: ${{ parameters.azureSubscription }}
              appType: 'apiApp'
              WebAppName: ${{ parameters.appName }}
              packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
