parameters:
  vmImage: 'ubuntu-latest'
  stageName: 'N/A'
  environment: 'N/A'
  dependsOn: 'N/A'
  appName: 'N/A'
  azureSubscription: 'N/A'
  resourceGroupName: 'N/A'
  appSettings: ''
  generalSettings: ''
  connectionStrings: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: '${{ parameters.stageName }} stage'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: 'Replace values in appsettings.json'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              appName: ${{ parameters.appName }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              appSettings: ${{ parameters.appSettings }}

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy in App Services'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: ${{ parameters.azureSubscription }}
              appType: 'apiApp'
              WebAppName: ${{ parameters.appName }}
              packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
