parameters:
  - name: vmImage
    displayName: 'vmImage'
    type: string
    default: 'ubuntu-latest'

  - name: sonarCloudOrganizationName
    displayName: 'Organization name for SonarCloud'
    type: string
    default: 'N/A'

  - name: defaultBranch
    displayName: 'Name of the main branch'
    type: string
    default: 'master'

  - name: buildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'N/A'

  - name: artifactPackDirectory
    displayName: 'Pipeline Artifact publishing directory'
    type: string
    default: 'N/A'

  - name: internalFeed
    displayName: 'Internal dotnet artifact feed'
    type: string
    default: 'N/A'

  - name: codeCoverageSettingsFileName
    displayName: 'The Name of the code coverage settings file'
    type: string
    default: 'CodeCoverage.runsettings'

  - name: includeSonarcloudBuildBreaker
    displayName: 'Does Sonarcloud build breaker turn on?'
    type: boolean
    default: true

variables:
  isDefaultBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.defaultBranch }}')]

stages:
  - stage: Build
    displayName: 'Build'
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - template: 'git-versioning.yml'
            parameters:
              isDefaultBranch: variables.isDefaultBranch

          - task: SonarCloudPrepare@1
            displayName: 'Prepare analysis on SonarCloud'
            inputs:
              SonarCloud: 'SonarCloud'
              organization: '${{ parameters.sonarCloudOrganizationName }}'
              scannerMode: 'MSBuild'
              projectKey: '$(Build.DefinitionName)'
              projectName: '$(Build.DefinitionName)'
              extraProperties: |
                sonar.cs.opencover.reportsPaths="$(Agent.TempDirectory)/**/coverage.opencover.xml"
                sonar.coverage.exclusions="tools/build/*"

          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK'
            inputs:
              packageType: 'sdk'
              version: '3.x'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore from both NuGet and Azure Artifacts feeds'
            condition: and(eq(variables.isDefaultBranch, false), ne(variables['Build.Reason'], 'PullRequest'))
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
              vstsFeed: '${{ parameters.internalFeed }}'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore only from NuGet feed'
            condition: or(eq(variables.isDefaultBranch, true), eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration ${{ parameters.buildConfiguration }} /p:Version=$(Build.BuildNumber)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: 'test'
              projects: '**/*[Tt]ests/*.csproj'
              arguments: '--configuration ${{ parameters.buildConfiguration }} --settings $(System.DefaultWorkingDirectory)/${{ parameters.codeCoverageSettingsFileName }} --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true'

          - task: DotNetCoreCLI@2
            displayName: 'Install ReportGenerator tool'
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'install --tool-path . dotnet-reportgenerator-globaltool'

          - script: ./reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
            displayName: 'Create reports'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'

          # Temp solution because of issue with SonarCloud
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK 2.2.x for SonarCloud'
            inputs:
              packageType: 'sdk'
              version: '2.2.x'

          - task: SonarCloudAnalyze@1
            displayName: 'Run Code Analysis'

          - task: SonarCloudPublish@1
            displayName: 'Publish Quality Gate Result'
            inputs:
              pollingTimeoutSec: '300'

          - task: sonarcloud-buildbreaker@2
            displayName: 'Break build on quality gate failure'
            condition: eq(${{ parameters.includeSonarcloudBuildBreaker }}, true)
            inputs:
              SonarCloud: 'SonarCloud'
              organization: '${{ parameters.sonarCloudOrganizationName }}'

          - task: DotNetCoreCLI@2
            displayName: 'Pack .NET Core NuGet packages'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              packDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPackDirectory }}'
              versioningScheme: byEnvVar
              versionEnvVar: 'Build.BuildNumber'

          - template: 'git-tag-managing.yml'
            parameters:
              isDefaultBranch: $(isDefaultBranch)

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact: NuGet Packages'
            inputs:
              path: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPackDirectory }}'
              artifact: 'NuGet Packages'

  - stage: Artifacts
    displayName: 'Artifacts'
    dependsOn: Build
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - deployment: Publish
        displayName: 'Publish packages in Artifacts'
        environment: 'Artifacts'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'Push package in Artifacts'
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                    nuGetFeedType: 'internal'
                    publishVstsFeed: '${{ parameters.internalFeed }}'

  - stage: NuGet
    displayName: 'NuGet'
    dependsOn: Artifacts
    condition: and(succeeded(), eq(variables.isDefaultBranch, true))
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - deployment: Publish
        displayName: 'Publish packages'
        environment: 'NuGet'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                    nuGetFeedType: 'external'
                    publishFeedCredentials: 'NuGet'
