parameters:
  vmImage: 'ubuntu-latest'
  buildConfiguration: 'Release'
  stageName: 'N/A'

stages:
- stage: ${{ parameters.stageName }}
  displayName: '${{ parameters.stageName }} stage'
  pool:
    vmImage: ${{ parameters.vmImage }}
  jobs:
  - job: Publish
    displayName: 'Publish job'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish application'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'artifact'
