parameters:
  - name: vmImage
    displayName: 'vmImage'
    type: string
    default: 'ubuntu-latest'
  buildConfiguration: 'N/A'
  codeCoverageSettingsFileName: 'CodeCoverage.runsettings'
  nugetConfigPath: ''

stages:
- stage: Build
  displayName: 'Build'
  pool:
    vmImage: ${{ parameters.vmImage }}
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
      - template: build.yml
        parameters:
          buildConfiguration: ${{ parameters.buildConfiguration }}
          codeCoverageSettingsFileName: ${{ parameters.codeCoverageSettingsFileName }}
          nugetConfigPath: ${{ parameters.nugetConfigPath }}
