parameters:
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
  - name: buildConfiguration
    type: string
    default: 'N/A'
  - name: codeCoverageSettingsFullPath
    type: string
    default: 'CodeCoverage.runsettings'
  - name: nugetConfigPath
    type: string
    default: ''

stages:
- stage: Build
  displayName: 'Build'
  pool:
    vmImage: ${{ parameters.vmImage }}
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
      - template: 'build.yml'
        parameters:
          buildConfiguration: ${{ parameters.buildConfiguration }}
          codeCoverageSettingsFullPath: ${{ parameters.codeCoverageSettingsFullPath }}
          nugetConfigPath: ${{ parameters.nugetConfigPath }}
