parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: environmentName
  type: string
  default: ''

- name: ciPipelineResourceName
  displayName: 'CI pipeline resource name'
  type: string
  default: 'ci'

- name: dependsOn
  displayName: 'Depends On'
  type: object
  default: []

- name: condition
  displayName: 'Condition'
  type: string
  default: 'succeeded()'

- name: projectArtifactName
  displayName: 'Project artifact name'
  type: string
  default: 'project'

- name: staticWebAppApiKey
  displayName: 'Static Web App Api Key'
  type: string
  default: ''

jobs:
- deployment: Deploy
  displayName: 'Deploy'
  pool:
    vmImage: ${{ parameters.vmImage }}
  environment: ${{ parameters.environmentName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ${{ parameters.ciPipelineResourceName }}
          displayName: 'Download artifact ''${{ parameters.projectArtifactName }}'''
          artifact: ${{ parameters.projectArtifactName }}

        - task: AzureStaticWebApp@0
          displayName: 'Deploy in Static Web App'
          inputs:
            workingDirectory: '$(Pipeline.Workspace)/${{ parameters.ciPipelineResourceName }}'
            app_location: '/${{ parameters.projectArtifactName }}'
            skip_app_build: true
            skip_api_build: true
            azure_static_web_apps_api_token: '${{ parameters.staticWebAppApiKey }}'
