parameters:
- name: vmImage
  displayName: 'Pool VM image'
  type: string
  default: 'ubuntu-latest'

- name: preBuildSteps
  displayName: 'Steps to run before build'
  type: stepList
  default: []

- name: enableSonarCloud
  displayName: 'Enable SonarCloud'
  type: boolean
  default: true

- name: sonarCloudOrganizationName
  displayName: 'Organization name for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectKey
  displayName: 'Project key for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectName
  displayName: 'Project name for SonarCloud'
  type: string
  default: ''

- name: checkWarnings
  displayName: 'Check warnings'
  type: boolean
  default: true

- name: checkCoverage
  displayName: 'Check code coverage'
  type: boolean
  default: true

- name: includeSonarcloudBuildBreaker
  displayName: 'Does Sonarcloud build breaker turn on?'
  type: boolean
  default: true

stages:
- stage: Build
  displayName: 'Build'

  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - template: 'build.yml'
      parameters:
        preBuildSteps: ${{ parameters.preBuildSteps }}
        enableSonarCloud: ${{ parameters.enableSonarCloud }}
        sonarCloudOrganizationName: ${{ parameters.sonarCloudOrganizationName }}
        sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
        sonarCloudProjectName: ${{ parameters.sonarCloudProjectName }}
        checkWarnings: ${{ parameters.checkWarnings }}
        checkCoverage: ${{ parameters.checkCoverage }}
        includeSonarcloudBuildBreaker: ${{ parameters.includeSonarcloudBuildBreaker }}
        