parameters:
- name: buildConfiguration
  displayName: 'Build configuration'
  type: string
  default: 'Release'

- name: preBuildSteps
  displayName: 'Steps to run before build'
  type: stepList
  default: []

- name: enableSonarCloud
  displayName: 'Enable SonarCloud'
  type: boolean
  default: true

- name: sonarCloudOrganizationName
  displayName: 'Organization name for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectKey
  displayName: 'Project key for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectName
  displayName: 'Project name for SonarCloud'
  type: string
  default: ''

- name: dotNetSDKVersions
  displayName: '.NET Core SDK versions'
  type: object
  default: []

- name: codeCoverageSettingsFullPath
  displayName: 'The path of the code coverage settings file'
  type: string
  default: '.runsettings'

- name: restoreOnlyFromNuGetFeed
  displayName: 'Restore only from NuGet feed'
  type: boolean
  default: true

- name: nugetConfigPath
  displayName: 'NuGet configuration path'
  type: string
  default: ''

- name: internalFeed
  displayName: 'Internal feed'
  type: string
  default: ''

- name: enableDotNetFormat
  displayName: 'Verify that all code is correctly formatted'
  type: boolean
  default: true

- name: continueOnErrorNuGetValidationOutdatedPackages
  displayName: 'Continue build if NuGet validation found outdated packages'
  type: boolean
  default: true

- name: mutationTestingLevel
  displayName: 'Mutation testing level'
  type: string
  default: 'Complete'

- name: mutationTestingProjects
  displayName: 'List of projects for mutation testing using Stryker'
  type: object
  default: []

- name: checkWarnings
  displayName: 'Check warnings'
  type: boolean
  default: true

- name: checkCoverage
  displayName: 'Check code coverage'
  type: boolean
  default: true

- name: includeSonarcloudBuildBreaker
  displayName: 'Does Sonarcloud build breaker turn on?'
  type: boolean
  default: true

- name: checkMutationTesting
  displayName: 'Check mutation testing'
  type: boolean
  default: true

steps:
- template: '../build.yml'
  parameters:
    buildConfiguration: ${{ parameters.buildConfiguration }}
    preBuildSteps: ${{ parameters.preBuildSteps }}
    enableSonarCloud: ${{ parameters.enableSonarCloud }}
    sonarCloudOrganizationName: ${{ parameters.sonarCloudOrganizationName }}
    sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
    sonarCloudProjectName: ${{ parameters.sonarCloudProjectName }}
    dotNetSDKVersions: ${{ parameters.dotNetSDKVersions }}
    codeCoverageSettingsFullPath: ${{ parameters.codeCoverageSettingsFullPath }}
    restoreOnlyFromNuGetFeed: ${{ parameters.restoreOnlyFromNuGetFeed }}
    nugetConfigPath: ${{ parameters.nugetConfigPath }}
    internalFeed: ${{ parameters.internalFeed }}
    enableDotNetFormat: ${{ parameters.enableDotNetFormat }}
    continueOnErrorNuGetValidationOutdatedPackages: ${{ parameters.continueOnErrorNuGetValidationOutdatedPackages }}
    mutationTestingLevel: ${{ parameters.mutationTestingLevel }}
    mutationTestingProjects: ${{ parameters.mutationTestingProjects }}
    checkWarnings: ${{ parameters.checkWarnings }}
    checkCoverage: ${{ parameters.checkCoverage }}
    includeSonarcloudBuildBreaker: ${{ parameters.includeSonarcloudBuildBreaker }}
    checkMutationTesting: ${{ parameters.checkMutationTesting }}
