parameters:
- name: buildConfiguration
  displayName: 'Build configuration'
  type: string
  default: 'Release'

- name: preBuildSteps
  displayName: 'Steps to run before build'
  type: stepList
  default: []

- name: enableSonarCloud
  displayName: 'Enable SonarCloud'
  type: boolean
  default: true

- name: sonarCloudOrganizationName
  displayName: 'Organization name for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectKey
  displayName: 'Project key for SonarCloud'
  type: string
  default: ''

- name: sonarCloudProjectName
  displayName: 'Project name for SonarCloud'
  type: string
  default: ''

- name: dotNetSDKVersions
  displayName: '.NET Core SDK versions'
  type: object
  default: []

- name: codeCoverageSettingsFullPath
  displayName: 'The path of the code coverage settings file'
  type: string
  default: '.runsettings'

- name: restoreOnlyFromNuGetFeed
  displayName: 'Restore only from NuGet feed'
  type: boolean
  default: true

- name: nugetConfigPath
  displayName: 'NuGet configuration path'
  type: string
  default: ''

- name: internalFeed
  displayName: 'Internal feed'
  type: string
  default: ''

- name: enableDotNetFormat
  displayName: 'Verify that all code is correctly formatted'
  type: boolean
  default: true

- name: mutationTestingProjects
  displayName: 'List of projects for mutation testing using Stryker'
  type: object
  default: []

- name: enableReSharperInspectCode
  displayName: 'Enable ReSharper inspect code'
  type: boolean
  default: true

- name: checkWarnings
  displayName: 'Check warnings'
  type: boolean
  default: true

- name: checkCoverage
  displayName: 'Check code coverage'
  type: boolean
  default: true

- name: includeSonarcloudBuildBreaker
  displayName: 'Does Sonarcloud build breaker turn on?'
  type: boolean
  default: true

steps:
# this task is here to solve issue of function build
# https://dev.to/kenakamu/build-net-5-azure-functions-with-azure-devops-pipeline-b7o
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    packageType: sdk
    version: '3.1.x'

- template: '../build.yml'
  parameters:
    buildConfiguration: ${{ parameters.buildConfiguration }}
    preBuildSteps: ${{ parameters.preBuildSteps }}
    enableSonarCloud: ${{ parameters.enableSonarCloud }}
    sonarCloudOrganizationName: ${{ parameters.sonarCloudOrganizationName }}
    sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
    sonarCloudProjectName: ${{ parameters.sonarCloudProjectName }}
    dotNetSDKVersions: ${{ parameters.dotNetSDKVersions }}
    codeCoverageSettingsFullPath: ${{ parameters.codeCoverageSettingsFullPath }}
    restoreOnlyFromNuGetFeed: ${{ parameters.restoreOnlyFromNuGetFeed }}
    nugetConfigPath: ${{ parameters.nugetConfigPath }}
    internalFeed: ${{ parameters.internalFeed }}
    enableDotNetFormat: ${{ parameters.enableDotNetFormat }}
    mutationTestingProjects: ${{ parameters.mutationTestingProjects }}
    enableReSharperInspectCode: ${{ parameters.enableReSharperInspectCode }}
    checkWarnings: ${{ parameters.checkWarnings }}
    checkCoverage: ${{ parameters.checkCoverage }}
    includeSonarcloudBuildBreaker: ${{ parameters.includeSonarcloudBuildBreaker }}
